import type { GamePackage } from "@/types/checklist"

export const gamePackages: Record<string, GamePackage> = {
  package1: {
    id: "package1",
    name: "Package 1",
    reels: "6x5",
    paylines: "Eight of a kind",
    maxWin: "21,000x bet",
    volatility: "Medium",
    minBet: 0.2,
    maxBet: 150.0,
    features: [
      "Free Spins (4+ Scatters)",
      "Bonus Game (3+ Scatters during Free Spins)",
      "Buy Bonus Feature",
      "Enhance Bet",
      "Tumble Wins",
    ],
    symbols: [
      { id: "s0", name: "Scatter", type: "Trigger", payouts: { "3": "3x", "5": "5x", "6": "100x" } },
      { id: "s1", name: "High Symbol 1", type: "High", payouts: { "8-9": "10x", "10-11": "25x", "12+": "50x" } },
      { id: "s10", name: "Multiplier", type: "Multiplier", payouts: { multiplier: "2x" } },
    ],
  },
  package2: {
    id: "package2",
    name: "Package 2",
    reels: "5x3",
    paylines: "20 Paylines",
    maxWin: "6,750x total bet",
    volatility: "High",
    minBet: 0.2,
    maxBet: 150.0,
    features: [
      "Free Spins (3+ Wild Symbols)",
      "Wheel Feature",
      "Wild Multipliers (Reels 2, 3, 4)",
      "Enhance Bet",
      "Buy Bonus Feature",
    ],
    symbols: [
      { id: "s0", name: "Scatter", type: "Scatter", payouts: { "3": "3x" } },
      { id: "s1", name: "Wild Multiplier", type: "Wild", payouts: { multiplier: "2x-3x" } },
    ],
  },
  package3: {
    id: "package3",
    name: "Package 3",
    reels: "6x5",
    paylines: "Eight of a kind",
    maxWin: "21,000x bet",
    volatility: "High",
    minBet: 0.2,
    maxBet: 150.0,
    features: [
      "Free Spins (4+ Scatters)",
      "Bonus Retrigger (3+ Scatters)",
      "Buy Bonus (15 Free Spins)",
      "Enhance Bet",
      "Tumble Wins",
    ],
    symbols: [
      { id: "s0", name: "Scatter", type: "Scatter", payouts: { "4": "3x", "5": "5x", "6": "100x" } },
      { id: "s1", name: "High Symbol", type: "High", payouts: { "8-9": "10x", "10-11": "25x", "12-30": "50x" } },
    ],
  },
  package4: {
    id: "package4",
    name: "Package 4",
    reels: "3x5",
    paylines: "10 Winlines",
    maxWin: "2,100x bet",
    volatility: "High",
    minBet: 0.2,
    maxBet: 150.0,
    features: [
      "Money Symbols (Fish)",
      "Free Spins (3+ Scatters)",
      "Wild Collection Mechanic",
      "Wild Bomb Feature",
      "Multiplier Retriggering",
    ],
    symbols: [
      { id: "s0", name: "Scatter", type: "Scatter", payouts: {} },
      { id: "s11", name: "Fish Symbol", type: "Money", payouts: { values: "2x-2000x" } },
      { id: "s18", name: "Wild/Collector", type: "Wild", payouts: { multiplier: "2x" } },
    ],
  },
  package5: {
    id: "package5",
    name: "Package 5",
    reels: "7x7",
    paylines: "5 Connected Horizontally/Vertically",
    maxWin: "2,100x bet",
    volatility: "Low",
    minBet: 0.2,
    maxBet: 150.0,
    features: ["Cascade Wins", "Free Spins (3+ Scatters)", "Multiplier Stacking", "Symbol Removal Mechanic"],
    symbols: [
      { id: "s0", name: "Scatter", type: "Scatter", payouts: { "3": "10FS", "4": "12FS", "5": "15FS" } },
      { id: "s1", name: "High Symbol", type: "High", payouts: { "5": "1.0x", "8": "2.5x", "15": "150x" } },
    ],
  },
}
